name: C/C++ CI

on: [pull_request]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: apt-get update && apt-get install libsixel-dev -y
    - name: make
      run: make
